param(
    [string]$BundleRoot = "artifacts",
    [string]$SourceChunks = "data\staging\chunks_2026-06-v2"
)

$ErrorActionPreference = "Stop"

$workspace = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $workspace

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$bundleDir = Join-Path $BundleRoot "server_enrichment_pilot_$timestamp"
$zipPath = "$bundleDir.zip"
$tarPath = "$bundleDir.tar.gz"

New-Item -ItemType Directory -Path $bundleDir -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $bundleDir "pharma_doc_pipeline") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $bundleDir "data\staging") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $bundleDir "docs") -Force | Out-Null

$files = @(
    "run_server_enrichment_pilot.py",
    "requirements.txt",
    "pharma_doc_pipeline\__init__.py",
    "pharma_doc_pipeline\config.py",
    "pharma_doc_pipeline\step_02_chunk.py",
    "pharma_doc_pipeline\step_03_enrich.py",
    "docs\enrichment_quality_audit_2026-06-10.md",
    "docs\enrichment_qa_todo_2026-06-10.md"
)

foreach ($file in $files) {
    if (Test-Path -LiteralPath $file) {
        $target = Join-Path $bundleDir $file
        New-Item -ItemType Directory -Path (Split-Path -Parent $target) -Force | Out-Null
        Copy-Item -LiteralPath $file -Destination $target -Force
    }
}

if (!(Test-Path -LiteralPath $SourceChunks)) {
    throw "Source chunks directory not found: $SourceChunks"
}

Copy-Item -LiteralPath $SourceChunks -Destination (Join-Path $bundleDir "data\staging") -Recurse -Force

$readme = @"
# Server Enrichment Pilot Bundle

This bundle runs a non-destructive model A/B enrichment pilot.

It contains:

- run_server_enrichment_pilot.py
- pharma_doc_pipeline/config.py
- pharma_doc_pipeline/step_02_chunk.py
- pharma_doc_pipeline/step_03_enrich.py
- data/staging/chunks_2026-06-v2/

Example Ollama run:

python3 run_server_enrichment_pilot.py \
  --backend ollama \
  --model "qwen3.6:27b" \
  --output data/staging/pilot_qwen36_27b

Example OpenAI-compatible API run:

python3 run_server_enrichment_pilot.py \
  --backend api \
  --api-base-url "http://127.0.0.1:8000/v1" \
  --api-key "EMPTY" \
  --model "deepseek-v4-flash" \
  --output data/staging/pilot_deepseek_v4_flash

Return the completed pilot output directories to the local machine for comparison.

On Linux servers, prefer the .tar.gz bundle generated by this script:

tar -xzf server_enrichment_pilot_<timestamp>.tar.gz
"@

$readmePath = Join-Path $bundleDir "SERVER_PILOT_README.md"
$readme | Set-Content -LiteralPath $readmePath -Encoding UTF8

Compress-Archive -LiteralPath $bundleDir -DestinationPath $zipPath -Force

if (Get-Command tar -ErrorAction SilentlyContinue) {
    $bundleLeaf = Split-Path -Leaf $bundleDir
    tar -czf $tarPath -C $BundleRoot $bundleLeaf
}

$resolvedTarPath = $null
if (Test-Path -LiteralPath $tarPath) {
    $resolvedTarPath = (Resolve-Path -LiteralPath $tarPath).Path
}

[pscustomobject]@{
    bundle_dir = (Resolve-Path -LiteralPath $bundleDir).Path
    zip_path = (Resolve-Path -LiteralPath $zipPath).Path
    tar_path = $resolvedTarPath
} | ConvertTo-Json -Depth 3
